AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Retrieval Service API - image-retrieval-service

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  UppercaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.smartinrubio.springbootawsserverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spring-boot-aws-serverless-0.0.1-SNAPSHOT.jar
      MemorySize: 256
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  UppercaseApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/uppercase'
    Export:
      Name: UppercaseApi